<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mice Development Team">
<meta name="dcterms.date" content="2024-06-28">

<title>mice: An approach to sensitivity analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="SenstivityAnalysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="SenstivityAnalysis_files/libs/quarto-html/quarto.js"></script>
<script src="SenstivityAnalysis_files/libs/quarto-html/popper.min.js"></script>
<script src="SenstivityAnalysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="SenstivityAnalysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="SenstivityAnalysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="SenstivityAnalysis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="SenstivityAnalysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="SenstivityAnalysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="SenstivityAnalysis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><code>mice</code>: An approach to sensitivity analysis</h1>
<p class="subtitle lead"><strong>Vignette 7 of 10</strong></p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p><strong>Mice Development Team</strong> </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 28, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<style type="text/css">

body{ /* Normal  */
      font-size: 16px;
  }
td {  /* Table  */
  font-size: 16px;
}
h1.title {
  font-size: 28px;
  color: Black;
}
h1 { /* Header 1 */
  font-size: 20px;
}
h2 { /* Header 2 */
    font-size: 18px;
}
h3 { /* Header 3 */
  font-size: 18px;
}
code.r{ /* Code block */
    font-size: 14px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>
<hr>
<p>This is the seventh vignette in the series.</p>
<p>The focus of this document is on sensitivity analysis in the context of missing data. The goal of sensitivity analysis is to study the influence that violations of the missingness assumptions have on the obtained inference.</p>
<hr>
<p><strong>Data set</strong></p>
<p>This is a synthetic dataset derived from 956 members of a very old (85+) cohort in Leiden. Unfortunately, we can not share the original leiden dataset with you. Thats why we have provided a synthetic version of leiden dataset. Multiple imputation of original leiden data set has been described in Boshuizen et al (1998), Van Buuren et al (1999) and Van Buuren (2012), chapter 7.</p>
<p>The main question is how blood pressure affects mortality risk in the oldest old. We have reasons to mistrust the MAR assumption in this case. In particular, we worried whether the imputations of blood pressure under MAR would be low enough. The sensitivity analysis explores the effect of artificially lowering the imputed blood pressure by deducting an amount of δ from the values imputed under MAR. In order to preserve the relations between the variables, this needs to be done during the iterations.</p>
<hr>
<p><strong>1. Open <code>R</code> and load the packages <code>mice</code>, <code>lattice</code> and <code>survival</code>.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"mice"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"lattice"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"survival"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<p><strong>2. Overview of data set.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(synthetic_leiden)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> sexe       lftanam           rrsyst       rrdiast            dwa        
 0:672   Min.   : 85.48   Min.   : 90   Min.   : 50.00   Min.   :0.0000  
 1:284   1st Qu.: 87.41   1st Qu.:135   1st Qu.: 75.00   1st Qu.:0.0000  
         Median : 89.03   Median :150   Median : 80.00   Median :0.0000  
         Mean   : 89.76   Mean   :152   Mean   : 82.49   Mean   :0.2312  
         3rd Qu.: 91.53   3rd Qu.:170   3rd Qu.: 90.00   3rd Qu.:0.0000  
         Max.   :103.54   Max.   :260   Max.   :135.00   Max.   :1.0000  
                          NA's   :121   NA's   :126                      
     survda            alb             chol             mmse       woon   
 Min.   :   2.0   Min.   :25.00   Min.   : 2.900   Min.   : 1.00   0:399  
 1st Qu.: 541.5   1st Qu.:39.00   1st Qu.: 4.800   1st Qu.:21.00   1: 35  
 Median :1175.5   Median :41.00   Median : 5.700   Median :26.00   2: 41  
 Mean   :1188.8   Mean   :40.71   Mean   : 5.704   Mean   :23.76   3:349  
 3rd Qu.:1875.0   3rd Qu.:43.00   3rd Qu.: 6.400   3rd Qu.:28.00   4:132  
 Max.   :2610.0   Max.   :49.00   Max.   :10.900   Max.   :30.00          
                  NA's   :229     NA's   :232      NA's   :85             </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(synthetic_leiden)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   956 obs. of  10 variables:
 $ sexe   : Factor w/ 2 levels "0","1": 1 1 2 1 1 1 1 2 1 1 ...
 $ lftanam: num  94.6 87.5 87.3 87 89.6 ...
 $ rrsyst : num  160 120 120 180 120 130 170 135 200 160 ...
 $ rrdiast: num  90 70 75 95 60 85 90 80 75 70 ...
 $ dwa    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ survda : num  1199 871 905 1035 300 ...
 $ alb    : num  38 NA 43 44 43 NA 39 NA 43 44 ...
 $ chol   : num  5.5 NA 4.2 5.3 6.7 NA 6.1 NA 5.3 7.3 ...
 $ mmse   : num  22 25 29 29 14 NA 28 30 25 14 ...
 $ woon   : Factor w/ 5 levels "0","1","2","3",..: 4 5 5 1 1 4 1 5 2 4 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(synthetic_leiden)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sexe lftanam rrsyst rrdiast dwa survda alb chol mmse woon
1    0   94.56    160      90   0   1199  38  5.5   22    3
2    0   87.48    120      70   0    871  NA   NA   25    4
3    1   87.32    120      75   0    905  43  4.2   29    4
4    0   87.05    180      95   0   1035  44  5.3   29    0
5    0   89.61    120      60   0    300  43  6.7   14    0
6    0   91.39    130      85   0    926  NA   NA   NA    3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(synthetic_leiden)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    sexe lftanam rrsyst rrdiast dwa survda alb chol mmse woon
951    1   92.30    125      80   0      6  42  2.9   15    0
952    0   94.64    190      80   0   1452  45  5.7   30    3
953    0   93.08    150      95   0    800  34  6.9   21    0
954    0   87.98    140      65   0    587  40  5.4   23    0
955    1   86.43    135      80   0    376  37  5.2   28    0
956    1   86.86    140      80   0    573  44  6.7   16    3</code></pre>
</div>
</div>
<hr>
<p><strong>3. Perform a dry run (using <code>maxit = 0</code>) in <code>mice</code>. List the number of missing values per variable.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>ini <span class="ot">&lt;-</span> <span class="fu">mice</span>(synthetic_leiden, <span class="at">maxit =</span> <span class="dv">0</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(ini<span class="sc">$</span>nmis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   sexe lftanam     dwa  survda    woon    mmse  rrsyst rrdiast     alb    chol 
      0       0       0       0       0      85     121     126     229     232 </code></pre>
</div>
</div>
<p>There are 121 missings (<code>NA</code>’s) for <code>rrsyst</code>, 126 missings for <code>rrdiast</code>, 229 missings for <code>alb</code>, 232 missings for <code>chol</code> and 85 missing values for <code>mmse</code>.</p>
<hr>
<p><strong>4. Study the missing data pattern in more detail using <code>md.pattern()</code> and <code>fluxplot()</code>. The interest here focusses on imputing systolic blood pressure (<code>rrsyst</code>) and diastolic blood pressure (<code>rrdiast</code>).</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">md.pattern</span>(synthetic_leiden)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SenstivityAnalysis_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    sexe lftanam dwa survda woon mmse rrsyst rrdiast alb chol    
621    1       1   1      1    1    1      1       1   1    1   0
2      1       1   1      1    1    1      1       1   1    0   1
1      1       1   1      1    1    1      1       1   0    1   1
149    1       1   1      1    1    1      1       1   0    0   2
2      1       1   1      1    1    1      1       0   1    1   1
2      1       1   1      1    1    1      1       0   0    0   3
72     1       1   1      1    1    1      0       0   1    1   2
2      1       1   1      1    1    1      0       0   1    0   3
20     1       1   1      1    1    1      0       0   0    0   4
21     1       1   1      1    1    0      1       1   1    1   1
36     1       1   1      1    1    0      1       1   0    0   3
1      1       1   1      1    1    0      1       0   0    0   4
7      1       1   1      1    1    0      0       0   1    1   3
20     1       1   1      1    1    0      0       0   0    0   5
       0       0   0      0    0   85    121     126 229  232 793</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>fx <span class="ot">&lt;-</span> <span class="fu">fluxplot</span>(synthetic_leiden)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SenstivityAnalysis_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Variables with higher outflux are (potentially) the more powerful predictors. Variables with higher influx depend stronger on the imputation model. When points are relatively close to the diagonal, it indicates that influx and outflux are balanced.</p>
<p>The variables in the upper left corner have the more complete information, so the number of missing data problems for this group is relatively small. The variables in the middle have an outflux between 0.5 and 0.8, which is small. Missing data problems are thus more severe, but potentially this group could also contain important variables. The lower (bottom) variables have an outflux with 0.5 or lower, so their predictive power is limited. Also, this group has a higher influx, and, thus, depend more highly on the imputation model.</p>
<p>If you’d like this information in tabulated form, you can simply ask</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>fx</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             pobs     influx   outflux      ainb       aout      fico
sexe    1.0000000 0.00000000 1.0000000 0.0000000 0.09216643 0.3504184
lftanam 1.0000000 0.00000000 1.0000000 0.0000000 0.09216643 0.3504184
rrsyst  0.8734310 0.09798107 0.5573770 0.7887971 0.05881570 0.2562874
rrdiast 0.8682008 0.10231550 0.5422446 0.7910053 0.05756359 0.2518072
dwa     1.0000000 0.00000000 1.0000000 0.0000000 0.09216643 0.3504184
survda  1.0000000 0.00000000 1.0000000 0.0000000 0.09216643 0.3504184
alb     0.7604603 0.19311053 0.2471627 0.8214459 0.02995568 0.1458047
chol    0.7573222 0.19573400 0.2383354 0.8218391 0.02900552 0.1422652
mmse    0.9110879 0.06798221 0.6796974 0.7790850 0.06875877 0.2870264
woon    1.0000000 0.00000000 1.0000000 0.0000000 0.09216643 0.3504184</code></pre>
</div>
</div>
<hr>
<p><strong>5. The cases with and without blood pressure observed have very different survival rates. Show this.</strong></p>
<p>We can see this easily from the Kaplan-Meier plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>synthetic_leiden<span class="sc">$</span>dwa <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(synthetic_leiden<span class="sc">$</span>dwa)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>km <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(survda<span class="sc">/</span><span class="dv">365</span>, dwa) <span class="sc">~</span> <span class="fu">is.na</span>(rrsyst), <span class="at">data =</span> synthetic_leiden) </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(km, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">lty  =</span> <span class="dv">1</span>, </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">lwd  =</span> <span class="fl">1.5</span>, </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Years since intake"</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"K-M Survival probability"</span>, <span class="at">las=</span><span class="dv">1</span>, </span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">col  =</span> <span class="fu">c</span>(<span class="fu">mdc</span>(<span class="dv">4</span>), <span class="fu">mdc</span>(<span class="dv">5</span>)), </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">mark.time =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">6.5</span>, <span class="fl">0.7</span>, <span class="st">"BP measured"</span>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">5</span>, <span class="fl">0.3</span>, <span class="st">"BP missing"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SenstivityAnalysis_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In the next steps we are going to impute <code>rrsyst</code> and <code>rrdiast</code> under two scenarios: MAR and MNAR. We will use the delta adjustment technique described in paragraph 7.2.3 in Van Buuren (2012)</p>
<hr>
<p><strong>6. Create a</strong> <span class="math inline">\(\delta\)</span> vector that represent the following adjustment values for mmHg: 0 for MAR, and -5, -10, -15, and -20 for MNAR.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>delta <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="sc">-</span><span class="dv">5</span>, <span class="sc">-</span><span class="dv">10</span>, <span class="sc">-</span><span class="dv">15</span>, <span class="sc">-</span><span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The recipe for creating MNAR imputations for <span class="math inline">\(\delta \neq 0\)</span> uses the post-processing facility of mice. This allows to change the imputations on the fly by deducting a value of <span class="math inline">\(\delta\)</span> from the values just imputed.</p>
<hr>
<p><strong>7. Impute the leiden data using the delta adjustment technique. We only have to deduct from <code>rrsyst</code>, because <code>rrdiast</code> will adapt to the changed <code>rrsyst</code> when it is imputed using <code>rrsyst</code> as predictor. Store the five imputed scenarios (adjustment) in a list called <code>imp.all</code>.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>imp.all <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"list"</span>, <span class="fu">length</span>(delta))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> ini<span class="sc">$</span>post</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(delta)){</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> delta[i]</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  cmd <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"imp[[j]][,i] &lt;- imp[[j]][,i] +"</span>, d)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  post[<span class="st">"rrsyst"</span>] <span class="ot">&lt;-</span> cmd</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(synthetic_leiden, <span class="at">post =</span> post, <span class="at">maxit =</span> <span class="dv">5</span>, <span class="at">seed =</span> i, <span class="at">print =</span> <span class="cn">FALSE</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  imp.all[[i]] <span class="ot">&lt;-</span> imp</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<p><strong>8. Inspect the imputations. Compare the imputations for blood pressure under the most extreme scenarios with a box-and-whiskers plot. Is this as expected?</strong></p>
<p>For the scenario where <span class="math inline">\(\delta = 0\)</span> we can plot the first object from the list. This object is the <code>mids</code>-object that considers imputations under no adjustment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(imp.all[[<span class="dv">1</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SenstivityAnalysis_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For the scenario where <span class="math inline">\(\delta = -20\)</span> we can plot the fifth object from the list. This object is the <code>mids</code>-object that considers imputations under the largest adjustment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(imp.all[[<span class="dv">5</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SenstivityAnalysis_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can clearly see that the adjustment has an effect on the imputations for <code>rrsyst</code> and, thus, on those for <code>rrdiast</code>.</p>
<hr>
<p><strong>9. Use the density plot for another inspection.</strong></p>
<p>For the scenario where<span class="math inline">\(\delta = 0\)</span> we can plot the first object from the list. This object is the <code>mids</code>-object that considers imputations under no adjustment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">densityplot</span>(imp.all[[<span class="dv">1</span>]], <span class="at">lwd =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SenstivityAnalysis_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For the scenario where <span class="math inline">\(\delta = -20\)</span> we can plot the fifth object from the list. This object is the <code>mids</code>-object that considers imputations under the largest adjustment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">densityplot</span>(imp.all[[<span class="dv">5</span>]], <span class="at">lwd =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SenstivityAnalysis_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can once more clearly see that the adjustment has an effect on the imputations for <code>rrsyst</code> and, thus, on those for <code>rrdiast</code>.</p>
<hr>
<p><strong>10. Also create a scatter plot of <code>rrsyst</code> and <code>rrdiast</code> by imputation number and missingness.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(imp.all[[<span class="dv">1</span>]], rrsyst <span class="sc">~</span> rrdiast <span class="sc">|</span> .imp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SenstivityAnalysis_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xyplot</span>(imp.all[[<span class="dv">5</span>]], rrsyst <span class="sc">~</span> rrdiast <span class="sc">|</span> .imp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SenstivityAnalysis_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The scatter plot comparison between <code>rrsyst</code> and <code>rrdiast</code> shows us that the adjustment has an effect on the imputations and that the imputations are lower for the situation where <span class="math inline">\(\delta = -20\)</span>.</p>
<hr>
<p>We are now going to perform a complete-data analysis. This involves several steps:</p>
<ol type="1">
<li>Create two categorical variables sbpgp and agegp that divide the observations into groups based on, respectively, systolic blood pressure and age.</li>
<li>Calculate whether person died or not.</li>
<li>Fit a Cox proportional hazards model to estimate the relative mortality risk corrected for sex and age group.</li>
</ol>
<p>In order to automate this step we should create an expression object that performs these stepd for us. The following object does so:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>cda <span class="ot">&lt;-</span> <span class="fu">expression</span>(</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  sbpgp <span class="ot">&lt;-</span> <span class="fu">cut</span>(rrsyst, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">124</span>, <span class="dv">144</span>, <span class="dv">164</span>, <span class="dv">184</span>, <span class="dv">200</span>, <span class="dv">500</span>)),</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  agegp <span class="ot">&lt;-</span> <span class="fu">cut</span>(lftanam, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">85</span>, <span class="dv">90</span>, <span class="dv">95</span>, <span class="dv">110</span>)),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  dead  <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> dwa,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coxph</span>(<span class="fu">Surv</span>(survda, dead) <span class="sc">~</span> <span class="fu">C</span>(sbpgp, <span class="fu">contr.treatment</span>(<span class="dv">6</span>, <span class="at">base =</span> <span class="dv">3</span>)) <span class="sc">+</span> <span class="fu">strata</span>(sexe, agegp))</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>See Van Buuren (2012, pp.186) for more information.</p>
<hr>
<p><strong>11. Create five fit objects that run the expression <code>cda</code> on the five imputed adjustment scenarios. Use function with().</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">with</span>(imp.all[[<span class="dv">1</span>]], cda)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">with</span>(imp.all[[<span class="dv">2</span>]], cda)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>fit3 <span class="ot">&lt;-</span> <span class="fu">with</span>(imp.all[[<span class="dv">3</span>]], cda)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>fit4 <span class="ot">&lt;-</span> <span class="fu">with</span>(imp.all[[<span class="dv">4</span>]], cda)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>fit5 <span class="ot">&lt;-</span> <span class="fu">with</span>(imp.all[[<span class="dv">5</span>]], cda)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Each fit object contains the five imputed Cox proportional hazards models for the adjustment scenario at hand. For example, the <span class="math inline">\(\delta=-10\)</span> scenario is contained in fit3.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>fit3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>call :
with.mids(data = imp.all[[3]], expr = cda)

call1 :
mice(data = synthetic_leiden, post = post, maxit = 5, printFlag = FALSE, 
    seed = i)

nmis :
   sexe lftanam  rrsyst rrdiast     dwa  survda     alb    chol    mmse    woon 
      0       0     121     126       0       0     229     232      85       0 

analyses :
[[1]]
Call:
coxph(formula = Surv(survda, dead) ~ C(sbpgp, contr.treatment(6, 
    base = 3)) + strata(sexe, agegp))

                                            coef exp(coef) se(coef)      z
C(sbpgp, contr.treatment(6, base = 3))1  0.48788   1.62886  0.11376  4.289
C(sbpgp, contr.treatment(6, base = 3))2  0.27687   1.31899  0.10209  2.712
C(sbpgp, contr.treatment(6, base = 3))4  0.15158   1.16367  0.11738  1.291
C(sbpgp, contr.treatment(6, base = 3))5  0.02372   1.02401  0.14105  0.168
C(sbpgp, contr.treatment(6, base = 3))6 -0.21825   0.80392  0.34220 -0.638
                                              p
C(sbpgp, contr.treatment(6, base = 3))1 1.8e-05
C(sbpgp, contr.treatment(6, base = 3))2 0.00669
C(sbpgp, contr.treatment(6, base = 3))4 0.19660
C(sbpgp, contr.treatment(6, base = 3))5 0.86644
C(sbpgp, contr.treatment(6, base = 3))6 0.52362

Likelihood ratio test=22.93  on 5 df, p=0.000348
n= 956, number of events= 735 

[[2]]
Call:
coxph(formula = Surv(survda, dead) ~ C(sbpgp, contr.treatment(6, 
    base = 3)) + strata(sexe, agegp))

                                            coef exp(coef) se(coef)      z
C(sbpgp, contr.treatment(6, base = 3))1  0.39924   1.49070  0.11408  3.500
C(sbpgp, contr.treatment(6, base = 3))2  0.37326   1.45246  0.10195  3.661
C(sbpgp, contr.treatment(6, base = 3))4  0.13042   1.13930  0.11917  1.094
C(sbpgp, contr.treatment(6, base = 3))5  0.05550   1.05707  0.14221  0.390
C(sbpgp, contr.treatment(6, base = 3))6 -0.07855   0.92446  0.34216 -0.230
                                               p
C(sbpgp, contr.treatment(6, base = 3))1 0.000466
C(sbpgp, contr.treatment(6, base = 3))2 0.000251
C(sbpgp, contr.treatment(6, base = 3))4 0.273796
C(sbpgp, contr.treatment(6, base = 3))5 0.696353
C(sbpgp, contr.treatment(6, base = 3))6 0.818434

Likelihood ratio test=20.93  on 5 df, p=0.0008343
n= 956, number of events= 735 

[[3]]
Call:
coxph(formula = Surv(survda, dead) ~ C(sbpgp, contr.treatment(6, 
    base = 3)) + strata(sexe, agegp))

                                            coef exp(coef) se(coef)      z
C(sbpgp, contr.treatment(6, base = 3))1  0.42758   1.53355  0.11396  3.752
C(sbpgp, contr.treatment(6, base = 3))2  0.29895   1.34844  0.10246  2.918
C(sbpgp, contr.treatment(6, base = 3))4  0.16385   1.17804  0.11712  1.399
C(sbpgp, contr.treatment(6, base = 3))5  0.03112   1.03161  0.14253  0.218
C(sbpgp, contr.treatment(6, base = 3))6 -0.09107   0.91296  0.34192 -0.266
                                               p
C(sbpgp, contr.treatment(6, base = 3))1 0.000175
C(sbpgp, contr.treatment(6, base = 3))2 0.003525
C(sbpgp, contr.treatment(6, base = 3))4 0.161801
C(sbpgp, contr.treatment(6, base = 3))5 0.827175
C(sbpgp, contr.treatment(6, base = 3))6 0.789979

Likelihood ratio test=18.6  on 5 df, p=0.002282
n= 956, number of events= 735 

[[4]]
Call:
coxph(formula = Surv(survda, dead) ~ C(sbpgp, contr.treatment(6, 
    base = 3)) + strata(sexe, agegp))

                                             coef exp(coef)  se(coef)      z
C(sbpgp, contr.treatment(6, base = 3))1  0.396511  1.486629  0.114339  3.468
C(sbpgp, contr.treatment(6, base = 3))2  0.307997  1.360697  0.101600  3.031
C(sbpgp, contr.treatment(6, base = 3))4  0.153366  1.165752  0.116203  1.320
C(sbpgp, contr.treatment(6, base = 3))5  0.006772  1.006795  0.142059  0.048
C(sbpgp, contr.treatment(6, base = 3))6 -0.100275  0.904588  0.341764 -0.293
                                               p
C(sbpgp, contr.treatment(6, base = 3))1 0.000525
C(sbpgp, contr.treatment(6, base = 3))2 0.002434
C(sbpgp, contr.treatment(6, base = 3))4 0.186897
C(sbpgp, contr.treatment(6, base = 3))5 0.961979
C(sbpgp, contr.treatment(6, base = 3))6 0.769212

Likelihood ratio test=17.9  on 5 df, p=0.00307
n= 956, number of events= 735 

[[5]]
Call:
coxph(formula = Surv(survda, dead) ~ C(sbpgp, contr.treatment(6, 
    base = 3)) + strata(sexe, agegp))

                                            coef exp(coef) se(coef)      z
C(sbpgp, contr.treatment(6, base = 3))1  0.40865   1.50479  0.11365  3.596
C(sbpgp, contr.treatment(6, base = 3))2  0.28764   1.33328  0.10079  2.854
C(sbpgp, contr.treatment(6, base = 3))4  0.14105   1.15148  0.11677  1.208
C(sbpgp, contr.treatment(6, base = 3))5  0.01149   1.01156  0.14236  0.081
C(sbpgp, contr.treatment(6, base = 3))6 -0.10340   0.90177  0.34168 -0.303
                                               p
C(sbpgp, contr.treatment(6, base = 3))1 0.000323
C(sbpgp, contr.treatment(6, base = 3))2 0.004320
C(sbpgp, contr.treatment(6, base = 3))4 0.227072
C(sbpgp, contr.treatment(6, base = 3))5 0.935670
C(sbpgp, contr.treatment(6, base = 3))6 0.762181

Likelihood ratio test=17.79  on 5 df, p=0.003218
n= 956, number of events= 735 </code></pre>
</div>
</div>
<hr>
<p><strong>12. Pool the results for each of the five scenarios.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>r1 <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">t</span>(<span class="fu">exp</span>(<span class="fu">summary</span>(<span class="fu">pool</span>(fit1))[, <span class="fu">c</span>(<span class="dv">2</span>)])))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>r2 <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">t</span>(<span class="fu">exp</span>(<span class="fu">summary</span>(<span class="fu">pool</span>(fit2))[, <span class="fu">c</span>(<span class="dv">2</span>)])))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>r3 <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">t</span>(<span class="fu">exp</span>(<span class="fu">summary</span>(<span class="fu">pool</span>(fit3))[, <span class="fu">c</span>(<span class="dv">2</span>)])))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>r4 <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">t</span>(<span class="fu">exp</span>(<span class="fu">summary</span>(<span class="fu">pool</span>(fit4))[, <span class="fu">c</span>(<span class="dv">2</span>)])))</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>r5 <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">t</span>(<span class="fu">exp</span>(<span class="fu">summary</span>(<span class="fu">pool</span>(fit5))[, <span class="fu">c</span>(<span class="dv">2</span>)])))</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">pool</span>(fit1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                     term     estimate std.error   statistic
1 C(sbpgp, contr.treatment(6, base = 3))1  0.384561979 0.1210874  3.17590376
2 C(sbpgp, contr.treatment(6, base = 3))2  0.273964679 0.1137322  2.40885787
3 C(sbpgp, contr.treatment(6, base = 3))4  0.101681327 0.1146571  0.88682971
4 C(sbpgp, contr.treatment(6, base = 3))5  0.003223223 0.1372274  0.02348819
5 C(sbpgp, contr.treatment(6, base = 3))6 -0.117472167 0.3319156 -0.35392175
         df     p.value
1 307.39511 0.001645321
2  78.83454 0.018335658
3 720.90741 0.375466336
4 626.37618 0.981268339
5 568.42823 0.723528764</code></pre>
</div>
</div>
<p>This code grabs the information from the tabulated pooled results that are produced by summary. In order to make sense about these numbers, and to see what exactly is extracted in the above code, laying out the numbers in a proper table may be useful.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>pars <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">t</span>(<span class="fu">matrix</span>(<span class="fu">c</span>(r1,r2,r3,r4,r5), <span class="at">nrow =</span> <span class="dv">5</span>)),<span class="dv">2</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>pars <span class="ot">&lt;-</span> pars[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span>)]</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dimnames</span>(pars) <span class="ot">&lt;-</span> <span class="fu">list</span>(delta, <span class="fu">c</span>(<span class="st">"&lt;125"</span>, <span class="st">"125-140"</span>, <span class="st">"&gt;200"</span>))</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>pars</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    &lt;125 125-140 &gt;200
0   1.47    1.32 0.89
-5  1.52    1.36 0.91
-10 1.53    1.36 0.89
-15 1.50    1.39 0.91
-20 1.58    1.37 0.92</code></pre>
</div>
</div>
<p>All in all, it seems that even big changes to the imputations (e.g.&nbsp;deducting 20 mmHg) has little influence on the results. This suggests that the results are stable relatively to this type of MNAR-mechanism.</p>
<hr>
<p><strong>13. Perform sensitivity analysis analysis on the mammalsleep dataset by adding and subtracting some amount from the imputed values for sws. Use delta &lt;- c(8, 6, 4, 2, 0, -2, -4, -6, -8) and investigating the influence on the following regression model:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(sws <span class="sc">~</span> <span class="fu">log10</span>(bw) <span class="sc">+</span> odi, <span class="at">data =</span> mammalsleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Sensitivity analysis is an important tool for investigating the plausibility of the MAR assumption. We again use the <span class="math inline">\(\delta\)</span>-adjustment technique described in Van Buuren (2012, p.&nbsp;185) as an informal, simple and direct method to create imputations under nonignorable models. We do so by simply adding and substracting some amount from the imputations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>delta <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">6</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">0</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="sc">-</span><span class="dv">4</span>, <span class="sc">-</span><span class="dv">6</span>, <span class="sc">-</span><span class="dv">8</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>ini <span class="ot">&lt;-</span> <span class="fu">mice</span>(mammalsleep[, <span class="sc">-</span><span class="dv">1</span>], <span class="at">maxit=</span><span class="dv">0</span>, <span class="at">print=</span>F)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>meth<span class="ot">&lt;-</span> ini<span class="sc">$</span>meth</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>meth[<span class="st">"ts"</span>]<span class="ot">&lt;-</span> <span class="st">"~ I(sws + ps)"</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> ini<span class="sc">$</span>pred</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>pred[<span class="fu">c</span>(<span class="st">"sws"</span>, <span class="st">"ps"</span>), <span class="st">"ts"</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> ini<span class="sc">$</span>post</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>imp.all.undamped <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"list"</span>, <span class="fu">length</span>(delta))</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(delta)) {</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> delta[i]</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  cmd <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"imp[[j]][, i] &lt;- imp[[j]][, i] +"</span>, d)</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>  post[<span class="st">"sws"</span>] <span class="ot">&lt;-</span> cmd</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>  imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(mammalsleep[, <span class="sc">-</span><span class="dv">1</span>], <span class="at">meth=</span>meth, <span class="at">pred=</span>pred, <span class="at">post =</span> post, <span class="at">maxit =</span> <span class="dv">10</span>, <span class="at">seed =</span> i <span class="sc">*</span> <span class="dv">22</span>, <span class="at">print=</span><span class="cn">FALSE</span>)</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>  imp.all.undamped[[i]] <span class="ot">&lt;-</span> imp</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>output <span class="ot">&lt;-</span> <span class="fu">sapply</span>(imp.all.undamped, <span class="cf">function</span>(x) <span class="fu">pool</span>(<span class="fu">with</span>(x, <span class="fu">lm</span>(sws <span class="sc">~</span> <span class="fu">log10</span>(bw) <span class="sc">+</span> odi)))<span class="sc">$</span>pooled<span class="sc">$</span>estimate)</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(output) <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">pool</span>(<span class="fu">with</span>(imp.all.undamped[[<span class="dv">1</span>]], <span class="fu">lm</span>(sws <span class="sc">~</span> <span class="fu">log10</span>(bw) <span class="sc">+</span> odi))))<span class="sc">$</span>term</span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(delta, <span class="fu">as.data.frame</span>(<span class="fu">t</span>(output)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  delta (Intercept)  log10(bw)        odi
1     8    13.38503 -0.1349983 -1.1122847
2     6    12.96965 -0.2546588 -1.1249810
3     4    12.47611 -0.6279854 -0.9881585
4     2    12.18507 -0.8777009 -1.0337294
5     0    11.79013 -0.9135497 -0.9815233
6    -2    11.16237 -1.4025229 -0.8425622
7    -4    10.78238 -1.6825684 -0.8408006
8    -6    10.55405 -1.8748218 -0.8283291
9    -8    10.10635 -2.1090423 -0.8664012</code></pre>
</div>
</div>
<p>The estimates for different <span class="math inline">\(\delta\)</span> are not close. A clear trend for the estimates for the <code>intercept</code> and for <code>bw</code> emerges. Thus, the results are not essentially the same under all specified mechanisms and the outcomes can be deemed sensitive to the assumed mechanism.</p>
<p>However, in this scenario, the <span class="math inline">\(\delta\)</span> adjustment is completely unrealistic. If we look at the descriptive information for observed <code>sws</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mammalsleep<span class="sc">$</span>sws)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  2.100   6.250   8.350   8.673  11.000  17.900      14 </code></pre>
</div>
</div>
<p>we find that even our smallest adjustment (<span class="math inline">\(\delta=|2|\)</span>) already makes up almost a quarter of the average <code>sws</code>. Choosing unreasonably large values may always influence your estimates. Therefore; choosing values that are reasonable given your suspicions of an assumed breach of the MAR assumption is vital.</p>
<p>We only used a shift parameter here. In other applications, scale or shape parameters could be more natural (see e.g.&nbsp;Van Buuren (2012), Ch. 3.9.1). The calculations are easily adapted to such cases.</p>
<hr>
<p><strong>Conclusion</strong></p>
<p>We have seen that we can create multiple imputations in multivariate missing data problems that imitate deviations from MAR. The analysis used the <code>post</code> argument of the <code>mice()</code> function as a hook to alter the imputations just after they have been created by a univariate imputation function. The diagnostics shows that the trick works. The relative mortality estimates are however robust to this type of alteration.</p>
<hr>
<p><strong>References</strong></p>
<p>Van Buuren, S. (2012), Flexible Imputation of Missing Data. Chapman &amp; Hall/CRC, Boca Raton, FL. ISBN 9781439868249. <a href="https://www.crcpress.com/product/isbn/9781439868249">CRC Press</a>, <a href="http://www.amazon.com/Flexible-Imputation-Missing-Interdisciplinary-Statistics/dp/1439868247/ref=sr_1_1?ie=UTF8&amp;qid=1328972069&amp;sr=8-1">Amazon</a>.</p>
<hr>
<p><strong>- End of Vignette</strong></p>
<hr>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>