<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mice Development Team">
<meta name="dcterms.date" content="2024-06-28">
<meta name="description" content="Vignette 1 of 10">

<title>Ad hoc methods and mice</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Adhoc_methods_and_mice_files/libs/clipboard/clipboard.min.js"></script>
<script src="Adhoc_methods_and_mice_files/libs/quarto-html/quarto.js"></script>
<script src="Adhoc_methods_and_mice_files/libs/quarto-html/popper.min.js"></script>
<script src="Adhoc_methods_and_mice_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Adhoc_methods_and_mice_files/libs/quarto-html/anchor.min.js"></script>
<link href="Adhoc_methods_and_mice_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Adhoc_methods_and_mice_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Adhoc_methods_and_mice_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Adhoc_methods_and_mice_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Adhoc_methods_and_mice_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Ad hoc methods and <code>mice</code></h1>
</div>

<div>
  <div class="description">
    <strong>Vignette 1 of 10</strong>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p><strong>Mice Development Team</strong> </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 28, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<style type="text/css">

body{ /* Normal  */
      font-size: 16px;
  }
td {  /* Table  */
  font-size: 16px;
}
h1.title {
  font-size: 28px;
  color: Black;
}
h1 { /* Header 1 */
  font-size: 20px;
}
h2 { /* Header 2 */
    font-size: 18px;
}
h3 { /* Header 3 */
  font-size: 18px;
}
code.r{ /* Code block */
    font-size: 14px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>
<hr>
<p>This is the first vignette in a series of ten. It will give you an introduction to the <code>R</code>-package <code>mice</code>, an open-source tool for flexible imputation of incomplete data, developed by Stef van Buuren and Karin Groothuis-Oudshoorn (2011). Over the last decade, <code>mice</code> has become an important piece of imputation software, offering a very flexible environment for dealing with incomplete data. Moreover, the ability to integrate <code>mice</code> with other packages in <code>R</code>, and vice versa, offers many options for applied researchers.</p>
<p>The aim of this introduction is to enhance your understanding of multiple imputation, in general. You will learn how to multiply impute simple datasets and how to obtain the imputed data for further analysis. The main objective is to increase your knowledge and understanding on applications of multiple imputation.</p>
<p>No previous experience with <code>R</code> is required.</p>
<hr>
<section id="working-with-mice" class="level4">
<h4 class="anchored" data-anchor-id="working-with-mice">Working with mice</h4>
<hr>
<p><strong>1. Open <code>R</code> and load the packages <code>mice</code> and <code>lattice</code></strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(mice)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(lattice)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If <code>mice</code> is not yet installed, run:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"mice"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<p><strong>2. Inspect the incomplete data</strong></p>
<p>The <code>mice</code> package contains several datasets. Once the package is loaded, these datasets can be used. Have a look at the <code>nhanes</code> dataset (Schafer, 1997, Table 6.14) by typing</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>nhanes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   age  bmi hyp chl
1    1   NA  NA  NA
2    2 22.7   1 187
3    1   NA   1 187
4    3   NA  NA  NA
5    1 20.4   1 113
6    3   NA  NA 184
7    1 22.5   1 118
8    1 30.1   1 187
9    2 22.0   1 238
10   2   NA  NA  NA
11   1   NA  NA  NA
12   2   NA  NA  NA
13   3 21.7   1 206
14   2 28.7   2 204
15   1 29.6   1  NA
16   1   NA  NA  NA
17   3 27.2   2 284
18   2 26.3   2 199
19   1 35.3   1 218
20   3 25.5   2  NA
21   1   NA  NA  NA
22   1 33.2   1 229
23   1 27.5   1 131
24   3 24.9   1  NA
25   2 27.4   1 186</code></pre>
</div>
</div>
<p>The <code>nhanes</code> dataset is a small data set with non-monotone missing values. It contains 25 observations on four variables: <em>age group</em>, <em>body mass index</em>, <em>hypertension</em> and <em>cholesterol (mg/dL)</em>.</p>
<p>To learn more about the data, use one of the two following help commands:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(nhanes)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>?nhanes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<p><strong>3. Get an overview of the data by the <code>summary()</code> command:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nhanes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age            bmi             hyp             chl       
 Min.   :1.00   Min.   :20.40   Min.   :1.000   Min.   :113.0  
 1st Qu.:1.00   1st Qu.:22.65   1st Qu.:1.000   1st Qu.:185.0  
 Median :2.00   Median :26.75   Median :1.000   Median :187.0  
 Mean   :1.76   Mean   :26.56   Mean   :1.235   Mean   :191.4  
 3rd Qu.:2.00   3rd Qu.:28.93   3rd Qu.:1.000   3rd Qu.:212.0  
 Max.   :3.00   Max.   :35.30   Max.   :2.000   Max.   :284.0  
                NA's   :9       NA's   :8       NA's   :10     </code></pre>
</div>
</div>
<hr>
<p><strong>4. Inspect the missing data pattern</strong></p>
<p>Check the missingness pattern for the <code>nhanes</code> dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">md.pattern</span>(nhanes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Adhoc_methods_and_mice_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   age hyp bmi chl   
13   1   1   1   1  0
3    1   1   1   0  1
1    1   1   0   1  1
1    1   0   0   1  2
7    1   0   0   0  3
     0   8   9  10 27</code></pre>
</div>
</div>
<p>The missingness pattern shows that there are 27 missing values in total: 10 for <code>chl</code> , 9 for <code>bmi</code> and 8 for <code>hyp</code>. Moreover, there are thirteen completely observed rows, four rows with 1 missing, one row with 2 missings and seven rows with 3 missings. Looking at the missing data pattern is always useful (but may be difficult for datasets with many variables). It can give you an indication on how much information is missing and how the missingness is distributed.</p>
<hr>
<section id="ad-hoc-imputation-methods" class="level5">
<h5 class="anchored" data-anchor-id="ad-hoc-imputation-methods">Ad Hoc imputation methods</h5>
<hr>
<p><strong>5. Form a regression model where <code>age</code> is predicted from <code>bmi</code>. </strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">with</span>(nhanes, <span class="fu">lm</span>(age <span class="sc">~</span> bmi))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = age ~ bmi)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.2660 -0.5614 -0.1225  0.4660  1.2344 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  3.76718    1.31945   2.855   0.0127 *
bmi         -0.07359    0.04910  -1.499   0.1561  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8015 on 14 degrees of freedom
  (9 observations deleted due to missingness)
Multiple R-squared:  0.1383,    Adjusted R-squared:  0.07672 
F-statistic: 2.246 on 1 and 14 DF,  p-value: 0.1561</code></pre>
</div>
</div>
<hr>
<p><strong>6. Impute the missing data in the <code>nhanes</code> dataset with mean imputation. </strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(nhanes, <span class="at">method =</span> <span class="st">"mean"</span>, <span class="at">m =</span> <span class="dv">1</span>, <span class="at">maxit =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 iter imp variable
  1   1  bmi  hyp  chl</code></pre>
</div>
</div>
<p>The imputations are now done. As you can see, the algorithm ran for 1 iteration (<code>maxit = 1</code>) and presented us with only 1 imputation (<code>m = 1</code>) for each missing datum. This is correct, as substituting each missing data multiple times with the observed data mean would not make any sense (the inference would be equal, no matter which imputed dataset we would analyze). Likewise, more iterations would be computationally inefficient as the <em>observed</em> data mean does not change based on our imputations. We named the imputed object <code>imp</code> following the convention used in <code>mice</code>, but if you wish you can name it anything you’d like.</p>
<hr>
<p><strong>7. Explore the imputed data with the <code>complete()</code> function. What do you think the variable means are? What happened to the regression equation after imputation?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">complete</span>(imp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   age     bmi      hyp   chl
1    1 26.5625 1.235294 191.4
2    2 22.7000 1.000000 187.0
3    1 26.5625 1.000000 187.0
4    3 26.5625 1.235294 191.4
5    1 20.4000 1.000000 113.0
6    3 26.5625 1.235294 184.0
7    1 22.5000 1.000000 118.0
8    1 30.1000 1.000000 187.0
9    2 22.0000 1.000000 238.0
10   2 26.5625 1.235294 191.4
11   1 26.5625 1.235294 191.4
12   2 26.5625 1.235294 191.4
13   3 21.7000 1.000000 206.0
14   2 28.7000 2.000000 204.0
15   1 29.6000 1.000000 191.4
16   1 26.5625 1.235294 191.4
17   3 27.2000 2.000000 284.0
18   2 26.3000 2.000000 199.0
19   1 35.3000 1.000000 218.0
20   3 25.5000 2.000000 191.4
21   1 26.5625 1.235294 191.4
22   1 33.2000 1.000000 229.0
23   1 27.5000 1.000000 131.0
24   3 24.9000 1.000000 191.4
25   2 27.4000 1.000000 186.0</code></pre>
</div>
</div>
<p>We see the repetitive numbers <code>26.5625</code> for <code>bmi</code>, <code>1.2352594</code> for <code>hyp</code>, and <code>191.4</code> for <code>chl</code>. These can be confirmed as the means of the respective variables (columns):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colMeans</span>(nhanes, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       age        bmi        hyp        chl 
  1.760000  26.562500   1.235294 191.400000 </code></pre>
</div>
</div>
<p>We saw during the inspection of the missing data pattern that variable <code>age</code> has no missings. Therefore nothing is imputed for <code>age</code> because we would not want to alter the observed (and bonafide) values.</p>
<p>To inspect the regression model with the imputed data, run:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">with</span>(imp, <span class="fu">lm</span>(age <span class="sc">~</span> bmi))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term        estimate std.error statistic p.value  nobs df.residual
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;int&gt;       &lt;dbl&gt;
1 (Intercept)   3.71      1.33        2.80  0.0103    25          23
2 bmi          -0.0736    0.0497     -1.48  0.152     25          23</code></pre>
</div>
</div>
<p>It is clear that nothing changed, but then again this is not surprising as variable <code>bmi</code> is somewhat normally distributed and we are just adding weight to the mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">densityplot</span>(nhanes<span class="sc">$</span>bmi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Adhoc_methods_and_mice_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<p><strong>8. Impute the missing data in the <code>nhanes</code> dataset with regression imputation. </strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(nhanes, <span class="at">method =</span> <span class="st">"norm.predict"</span>, <span class="at">m =</span> <span class="dv">1</span>, <span class="at">maxit =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 iter imp variable
  1   1  bmi  hyp  chl</code></pre>
</div>
</div>
<p>The imputations are now done. This code imputes the missing values in the data set by the regression imputation method. The argument <code>method = "norm.predict"</code> first fits a regression model for each observed value, based on the corresponding values in other variables and then imputes the missing values with the predicted values.</p>
<hr>
<p><strong>9. Again, inspect the completed data and investigate the imputed data regression model. </strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">complete</span>(imp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   age      bmi       hyp      chl
1    1 28.36021 1.0474831 172.4557
2    2 22.70000 1.0000000 187.0000
3    1 28.36021 1.0000000 187.0000
4    3 22.80609 1.5088506 222.7836
5    1 20.40000 1.0000000 113.0000
6    3 22.68531 1.5019433 184.0000
7    1 22.50000 1.0000000 118.0000
8    1 30.10000 1.0000000 187.0000
9    2 22.00000 1.0000000 238.0000
10   2 27.04536 1.3053438 208.0862
11   1 29.82242 1.0746600 182.9223
12   2 25.46237 1.2712595 196.7785
13   3 21.70000 1.0000000 206.0000
14   2 28.70000 2.0000000 204.0000
15   1 29.60000 1.0000000 181.6849
16   1 25.58231 0.8886142 153.1107
17   3 27.20000 2.0000000 284.0000
18   2 26.30000 2.0000000 199.0000
19   1 35.30000 1.0000000 218.0000
20   3 25.50000 2.0000000 239.8485
21   1 28.31995 1.0451807 172.1753
22   1 33.20000 1.0000000 229.0000
23   1 27.50000 1.0000000 131.0000
24   3 24.90000 1.0000000 240.5268
25   2 27.40000 1.0000000 186.0000</code></pre>
</div>
</div>
<p>The repetitive numbering is gone. We have now obtained a more natural looking set of imputations: instead of filling in the same <code>bmi</code> for all ages, we now take <code>age</code> (as well as <code>hyp</code> and <code>chl</code>) into account when imputing <code>bmi</code>.</p>
<p>To inspect the regression model with the imputed data, run:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">with</span>(imp, <span class="fu">lm</span>(age <span class="sc">~</span> bmi))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term        estimate std.error statistic  p.value  nobs df.residual
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;       &lt;dbl&gt;
1 (Intercept)    4.68     1.12        4.20 0.000345    25          23
2 bmi           -0.110    0.0417     -2.64 0.0146      25          23</code></pre>
</div>
</div>
<p>It is clear that something has changed. In fact, we extrapolated (part of) the regression model for the observed data to missing data in <code>bmi</code>. In other words; the relation (read: information) gets stronger and we’ve obtained more observations.</p>
<hr>
<p><strong>10. Impute the missing data in the <code>nhanes</code> dataset with stochastic regression imputation.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(nhanes, <span class="at">method =</span> <span class="st">"norm.nob"</span>, <span class="at">m =</span> <span class="dv">1</span>, <span class="at">maxit =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 iter imp variable
  1   1  bmi  hyp  chl</code></pre>
</div>
</div>
<p>The imputations are now done. This code imputes the missing values in the data set by the stochastic regression imputation method. The function does not incorporate the variability of the regression weights, so it is not ‘proper’ in the sense of Rubin (1987). For small samples, the variability of the imputed data will be underestimated.</p>
<hr>
<p><strong>11. Again, inspect the completed data and investigate the imputed data regression model. </strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">complete</span>(imp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   age      bmi       hyp      chl
1    1 33.61471 1.0064774 200.0025
2    2 22.70000 1.0000000 187.0000
3    1 32.36556 1.0000000 187.0000
4    3 29.94711 1.2555111 291.6824
5    1 20.40000 1.0000000 113.0000
6    3 20.02676 1.5286735 184.0000
7    1 22.50000 1.0000000 118.0000
8    1 30.10000 1.0000000 187.0000
9    2 22.00000 1.0000000 238.0000
10   2 20.09440 0.9498627 192.3497
11   1 32.65078 1.1459837 211.3078
12   2 20.12858 1.3255888 148.9863
13   3 21.70000 1.0000000 206.0000
14   2 28.70000 2.0000000 204.0000
15   1 29.60000 1.0000000 210.7834
16   1 26.85249 0.7870282 187.5259
17   3 27.20000 2.0000000 284.0000
18   2 26.30000 2.0000000 199.0000
19   1 35.30000 1.0000000 218.0000
20   3 25.50000 2.0000000 261.4307
21   1 36.35340 1.4367806 230.8058
22   1 33.20000 1.0000000 229.0000
23   1 27.50000 1.0000000 131.0000
24   3 24.90000 1.0000000 228.5297
25   2 27.40000 1.0000000 186.0000</code></pre>
</div>
</div>
<p>We have once more obtained a more natural looking set of imputations, where instead of filling in the same <code>bmi</code> for all ages, we now take <code>age</code> (as well as <code>hyp</code> and <code>chl</code>) into account when imputing <code>bmi</code>. We also add a random error to allow for our imputations to be off the regression line.</p>
<p>To inspect the regression model with the imputed data, run:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">with</span>(imp, <span class="fu">lm</span>(age <span class="sc">~</span> bmi))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term        estimate std.error statistic   p.value  nobs df.residual
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;       &lt;dbl&gt;
1 (Intercept)   3.91      0.826       4.73 0.0000907    25          23
2 bmi          -0.0793    0.0300     -2.64 0.0145       25          23</code></pre>
</div>
</div>
<hr>
<p><strong>12. Re-run the stochastic imputation model with seed <code>123</code> and verify if your results are the same as the ones below</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term        estimate std.error statistic   p.value  nobs df.residual
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;       &lt;dbl&gt;
1 (Intercept)   3.75      0.736       5.10 0.0000362    25          23
2 bmi          -0.0792    0.0287     -2.77 0.0110       25          23</code></pre>
</div>
</div>
<p>The imputation procedure uses random sampling, and therefore, the results will be (perhaps slightly) different if we repeat the imputations. In order to get exactly the same result, you can use the seed argument</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(nhanes, <span class="at">method =</span> <span class="st">"norm.nob"</span>, <span class="at">m =</span> <span class="dv">1</span>, <span class="at">maxit =</span> <span class="dv">1</span>, <span class="at">seed =</span> <span class="dv">123</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">with</span>(imp, <span class="fu">lm</span>(age <span class="sc">~</span> bmi))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>where 123 is some arbitrary number that you can choose yourself. Re-running this command will always yields the same imputed values. The ability to replicate one’s findings exactly is considered essential in today’s reproducible science.</p>
<hr>
</section>
</section>
<section id="multiple-imputation" class="level4">
<h4 class="anchored" data-anchor-id="multiple-imputation">Multiple imputation</h4>
<hr>
<p><strong>13. Let us impute the missing data in the <code>nhanes</code> dataset</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(nhanes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 iter imp variable
  1   1  bmi  hyp  chl
  1   2  bmi  hyp  chl
  1   3  bmi  hyp  chl
  1   4  bmi  hyp  chl
  1   5  bmi  hyp  chl
  2   1  bmi  hyp  chl
  2   2  bmi  hyp  chl
  2   3  bmi  hyp  chl
  2   4  bmi  hyp  chl
  2   5  bmi  hyp  chl
  3   1  bmi  hyp  chl
  3   2  bmi  hyp  chl
  3   3  bmi  hyp  chl
  3   4  bmi  hyp  chl
  3   5  bmi  hyp  chl
  4   1  bmi  hyp  chl
  4   2  bmi  hyp  chl
  4   3  bmi  hyp  chl
  4   4  bmi  hyp  chl
  4   5  bmi  hyp  chl
  5   1  bmi  hyp  chl
  5   2  bmi  hyp  chl
  5   3  bmi  hyp  chl
  5   4  bmi  hyp  chl
  5   5  bmi  hyp  chl</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>imp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Class: mids
Number of multiple imputations:  5 
Imputation methods:
  age   bmi   hyp   chl 
   "" "pmm" "pmm" "pmm" 
PredictorMatrix:
    age bmi hyp chl
age   0   1   1   1
bmi   1   0   1   1
hyp   1   1   0   1
chl   1   1   1   0</code></pre>
</div>
</div>
<p>The imputations are now done. As you can see, the algorithm ran for 5 iterations (the default) and presented us with 5 imputations for each missing datum. For the rest of this document we will omit printing of the iteration cycle when we run <code>mice</code>. We do so by adding <code>print=F</code> to the <code>mice</code> call.</p>
<p>The object <code>imp</code> contains a multiply imputed data set (of class <code>mids</code>). It encapsulates all information from imputing the <code>nhanes</code> dataset, such as the original data, the imputed values, the number of missing values, number of iterations, and so on.</p>
<p>To obtain an overview of the information stored in the object <code>imp</code>, use the <code>attributes()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(imp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$names
 [1] "data"            "imp"             "m"               "where"          
 [5] "blocks"          "call"            "nmis"            "method"         
 [9] "predictorMatrix" "visitSequence"   "formulas"        "post"           
[13] "blots"           "ignore"          "seed"            "iteration"      
[17] "lastSeedValue"   "chainMean"       "chainVar"        "loggedEvents"   
[21] "version"         "date"           

$class
[1] "mids"</code></pre>
</div>
</div>
<p>For example, the original data are stored as</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>imp<span class="sc">$</span>data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   age  bmi hyp chl
1    1   NA  NA  NA
2    2 22.7   1 187
3    1   NA   1 187
4    3   NA  NA  NA
5    1 20.4   1 113
6    3   NA  NA 184
7    1 22.5   1 118
8    1 30.1   1 187
9    2 22.0   1 238
10   2   NA  NA  NA
11   1   NA  NA  NA
12   2   NA  NA  NA
13   3 21.7   1 206
14   2 28.7   2 204
15   1 29.6   1  NA
16   1   NA  NA  NA
17   3 27.2   2 284
18   2 26.3   2 199
19   1 35.3   1 218
20   3 25.5   2  NA
21   1   NA  NA  NA
22   1 33.2   1 229
23   1 27.5   1 131
24   3 24.9   1  NA
25   2 27.4   1 186</code></pre>
</div>
</div>
<p>and the imputations are stored as</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>imp<span class="sc">$</span>imp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$age
[1] 1 2 3 4 5
&lt;0 rows&gt; (or 0-length row.names)

$bmi
      1    2    3    4    5
1  24.9 25.5 27.4 22.0 28.7
3  28.7 22.0 29.6 28.7 22.0
4  27.4 29.6 20.4 25.5 20.4
6  25.5 21.7 24.9 20.4 27.4
10 21.7 20.4 27.4 27.5 28.7
11 22.5 33.2 22.0 33.2 35.3
12 27.2 27.5 27.5 27.2 22.5
16 30.1 22.5 27.5 30.1 27.2
21 30.1 30.1 28.7 28.7 22.0

$hyp
   1 2 3 4 5
1  1 1 1 1 1
4  2 1 2 1 1
6  2 2 2 2 2
10 2 1 1 1 1
11 1 1 1 1 1
12 1 2 1 2 1
16 1 1 1 1 1
21 1 1 1 1 1

$chl
     1   2   3   4   5
1  187 238 187 131 187
4  206 218 187 186 204
10 187 113 229 186 206
11 113 206 187 229 229
12 206 184 206 218 199
15 229 184 238 187 187
16 187 238 187 184 238
20 186 206 184 284 229
21 199 229 238 187 238
24 184 284 186 204 206</code></pre>
</div>
</div>
<hr>
<p><strong>14. Extract the completed data</strong></p>
<p>By default, <code>mice()</code> calculates five (<em>m</em> = 5) imputed data sets. In order to get the third imputed data set, use the <code>complete()</code> function</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>c3 <span class="ot">&lt;-</span> <span class="fu">complete</span>(imp, <span class="dv">3</span>) </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">md.pattern</span>(c3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> /\     /\
{  `---'  }
{  O   O  }
==&gt;  V &lt;==  No need for mice. This data set is completely observed.
 \  \|/  /
  `-----'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Adhoc_methods_and_mice_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   age bmi hyp chl  
25   1   1   1   1 0
     0   0   0   0 0</code></pre>
</div>
</div>
<p>The collection of the <span class="math inline">\(m\)</span> imputed data sets can be exported by function <code>complete()</code> in long, broad and repeated formats. For example,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>c.long <span class="ot">&lt;-</span> <span class="fu">complete</span>(imp, <span class="st">"long"</span>)  </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>c.long</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    age  bmi hyp chl .imp .id
1     1 24.9   1 187    1   1
2     2 22.7   1 187    1   2
3     1 28.7   1 187    1   3
4     3 27.4   2 206    1   4
5     1 20.4   1 113    1   5
6     3 25.5   2 184    1   6
7     1 22.5   1 118    1   7
8     1 30.1   1 187    1   8
9     2 22.0   1 238    1   9
10    2 21.7   2 187    1  10
11    1 22.5   1 113    1  11
12    2 27.2   1 206    1  12
13    3 21.7   1 206    1  13
14    2 28.7   2 204    1  14
15    1 29.6   1 229    1  15
16    1 30.1   1 187    1  16
17    3 27.2   2 284    1  17
18    2 26.3   2 199    1  18
19    1 35.3   1 218    1  19
20    3 25.5   2 186    1  20
21    1 30.1   1 199    1  21
22    1 33.2   1 229    1  22
23    1 27.5   1 131    1  23
24    3 24.9   1 184    1  24
25    2 27.4   1 186    1  25
26    1 25.5   1 238    2   1
27    2 22.7   1 187    2   2
28    1 22.0   1 187    2   3
29    3 29.6   1 218    2   4
30    1 20.4   1 113    2   5
31    3 21.7   2 184    2   6
32    1 22.5   1 118    2   7
33    1 30.1   1 187    2   8
34    2 22.0   1 238    2   9
35    2 20.4   1 113    2  10
36    1 33.2   1 206    2  11
37    2 27.5   2 184    2  12
38    3 21.7   1 206    2  13
39    2 28.7   2 204    2  14
40    1 29.6   1 184    2  15
41    1 22.5   1 238    2  16
42    3 27.2   2 284    2  17
43    2 26.3   2 199    2  18
44    1 35.3   1 218    2  19
45    3 25.5   2 206    2  20
46    1 30.1   1 229    2  21
47    1 33.2   1 229    2  22
48    1 27.5   1 131    2  23
49    3 24.9   1 284    2  24
50    2 27.4   1 186    2  25
51    1 27.4   1 187    3   1
52    2 22.7   1 187    3   2
53    1 29.6   1 187    3   3
54    3 20.4   2 187    3   4
55    1 20.4   1 113    3   5
56    3 24.9   2 184    3   6
57    1 22.5   1 118    3   7
58    1 30.1   1 187    3   8
59    2 22.0   1 238    3   9
60    2 27.4   1 229    3  10
61    1 22.0   1 187    3  11
62    2 27.5   1 206    3  12
63    3 21.7   1 206    3  13
64    2 28.7   2 204    3  14
65    1 29.6   1 238    3  15
66    1 27.5   1 187    3  16
67    3 27.2   2 284    3  17
68    2 26.3   2 199    3  18
69    1 35.3   1 218    3  19
70    3 25.5   2 184    3  20
71    1 28.7   1 238    3  21
72    1 33.2   1 229    3  22
73    1 27.5   1 131    3  23
74    3 24.9   1 186    3  24
75    2 27.4   1 186    3  25
76    1 22.0   1 131    4   1
77    2 22.7   1 187    4   2
78    1 28.7   1 187    4   3
79    3 25.5   1 186    4   4
80    1 20.4   1 113    4   5
81    3 20.4   2 184    4   6
82    1 22.5   1 118    4   7
83    1 30.1   1 187    4   8
84    2 22.0   1 238    4   9
85    2 27.5   1 186    4  10
86    1 33.2   1 229    4  11
87    2 27.2   2 218    4  12
88    3 21.7   1 206    4  13
89    2 28.7   2 204    4  14
90    1 29.6   1 187    4  15
91    1 30.1   1 184    4  16
92    3 27.2   2 284    4  17
93    2 26.3   2 199    4  18
94    1 35.3   1 218    4  19
95    3 25.5   2 284    4  20
96    1 28.7   1 187    4  21
97    1 33.2   1 229    4  22
98    1 27.5   1 131    4  23
99    3 24.9   1 204    4  24
100   2 27.4   1 186    4  25
101   1 28.7   1 187    5   1
102   2 22.7   1 187    5   2
103   1 22.0   1 187    5   3
104   3 20.4   1 204    5   4
105   1 20.4   1 113    5   5
106   3 27.4   2 184    5   6
107   1 22.5   1 118    5   7
108   1 30.1   1 187    5   8
109   2 22.0   1 238    5   9
110   2 28.7   1 206    5  10
111   1 35.3   1 229    5  11
112   2 22.5   1 199    5  12
113   3 21.7   1 206    5  13
114   2 28.7   2 204    5  14
115   1 29.6   1 187    5  15
116   1 27.2   1 238    5  16
117   3 27.2   2 284    5  17
118   2 26.3   2 199    5  18
119   1 35.3   1 218    5  19
120   3 25.5   2 229    5  20
121   1 22.0   1 238    5  21
122   1 33.2   1 229    5  22
123   1 27.5   1 131    5  23
124   3 24.9   1 206    5  24
125   2 27.4   1 186    5  25</code></pre>
</div>
</div>
<p>and</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>c.broad <span class="ot">&lt;-</span> <span class="fu">complete</span>(imp, <span class="st">"broad"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `age` -&gt; `age...1`
• `bmi` -&gt; `bmi...2`
• `hyp` -&gt; `hyp...3`
• `chl` -&gt; `chl...4`
• `age` -&gt; `age...5`
• `bmi` -&gt; `bmi...6`
• `hyp` -&gt; `hyp...7`
• `chl` -&gt; `chl...8`
• `age` -&gt; `age...9`
• `bmi` -&gt; `bmi...10`
• `hyp` -&gt; `hyp...11`
• `chl` -&gt; `chl...12`
• `age` -&gt; `age...13`
• `bmi` -&gt; `bmi...14`
• `hyp` -&gt; `hyp...15`
• `chl` -&gt; `chl...16`
• `age` -&gt; `age...17`
• `bmi` -&gt; `bmi...18`
• `hyp` -&gt; `hyp...19`
• `chl` -&gt; `chl...20`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>c.broad</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   age.1 bmi.1 hyp.1 chl.1 age.2 bmi.2 hyp.2 chl.2 age.3 bmi.3 hyp.3 chl.3
1      1  24.9     1   187     1  25.5     1   238     1  27.4     1   187
2      2  22.7     1   187     2  22.7     1   187     2  22.7     1   187
3      1  28.7     1   187     1  22.0     1   187     1  29.6     1   187
4      3  27.4     2   206     3  29.6     1   218     3  20.4     2   187
5      1  20.4     1   113     1  20.4     1   113     1  20.4     1   113
6      3  25.5     2   184     3  21.7     2   184     3  24.9     2   184
7      1  22.5     1   118     1  22.5     1   118     1  22.5     1   118
8      1  30.1     1   187     1  30.1     1   187     1  30.1     1   187
9      2  22.0     1   238     2  22.0     1   238     2  22.0     1   238
10     2  21.7     2   187     2  20.4     1   113     2  27.4     1   229
11     1  22.5     1   113     1  33.2     1   206     1  22.0     1   187
12     2  27.2     1   206     2  27.5     2   184     2  27.5     1   206
13     3  21.7     1   206     3  21.7     1   206     3  21.7     1   206
14     2  28.7     2   204     2  28.7     2   204     2  28.7     2   204
15     1  29.6     1   229     1  29.6     1   184     1  29.6     1   238
16     1  30.1     1   187     1  22.5     1   238     1  27.5     1   187
17     3  27.2     2   284     3  27.2     2   284     3  27.2     2   284
18     2  26.3     2   199     2  26.3     2   199     2  26.3     2   199
19     1  35.3     1   218     1  35.3     1   218     1  35.3     1   218
20     3  25.5     2   186     3  25.5     2   206     3  25.5     2   184
21     1  30.1     1   199     1  30.1     1   229     1  28.7     1   238
22     1  33.2     1   229     1  33.2     1   229     1  33.2     1   229
23     1  27.5     1   131     1  27.5     1   131     1  27.5     1   131
24     3  24.9     1   184     3  24.9     1   284     3  24.9     1   186
25     2  27.4     1   186     2  27.4     1   186     2  27.4     1   186
   age.4 bmi.4 hyp.4 chl.4 age.5 bmi.5 hyp.5 chl.5
1      1  22.0     1   131     1  28.7     1   187
2      2  22.7     1   187     2  22.7     1   187
3      1  28.7     1   187     1  22.0     1   187
4      3  25.5     1   186     3  20.4     1   204
5      1  20.4     1   113     1  20.4     1   113
6      3  20.4     2   184     3  27.4     2   184
7      1  22.5     1   118     1  22.5     1   118
8      1  30.1     1   187     1  30.1     1   187
9      2  22.0     1   238     2  22.0     1   238
10     2  27.5     1   186     2  28.7     1   206
11     1  33.2     1   229     1  35.3     1   229
12     2  27.2     2   218     2  22.5     1   199
13     3  21.7     1   206     3  21.7     1   206
14     2  28.7     2   204     2  28.7     2   204
15     1  29.6     1   187     1  29.6     1   187
16     1  30.1     1   184     1  27.2     1   238
17     3  27.2     2   284     3  27.2     2   284
18     2  26.3     2   199     2  26.3     2   199
19     1  35.3     1   218     1  35.3     1   218
20     3  25.5     2   284     3  25.5     2   229
21     1  28.7     1   187     1  22.0     1   238
22     1  33.2     1   229     1  33.2     1   229
23     1  27.5     1   131     1  27.5     1   131
24     3  24.9     1   204     3  24.9     1   206
25     2  27.4     1   186     2  27.4     1   186</code></pre>
</div>
</div>
<p>are completed data sets in long and broad format, respectively. See <code>?complete</code> for more detail.</p>
<hr>
<p><strong>Conclusion</strong></p>
<p>We have seen that (multiple) imputation is straightforward with <code>mice</code>. However, don’t let the simplicity of the software fool you into thinking that the problem itself is also straightforward. In the next vignette we will therefore explore how the mice package can flexibly provide us the tools to assess and control the imputation of missing data.</p>
<hr>
<p><strong>References</strong></p>
<p>Rubin, D. B. <em>Multiple imputation for nonresponse in surveys</em>. John Wiley &amp; Sons, 1987. <a href="http://www.amazon.com/Multiple-Imputation-Nonresponse-Surveys-Donald/dp/0471655740/ref=sr_1_1?ie=UTF8&amp;qid=1434466788&amp;sr=8-1&amp;keywords=Multiple+imputation+for+nonresponse+in+surveys">Amazon</a></p>
<p>Schafer, J.L. (1997). <em>Analysis of Incomplete Multivariate Data</em>. London: Chapman &amp; Hall. Table 6.14. <a href="http://www.amazon.com/Incomplete-Multivariate-Monographs-Statistics-Probability/dp/0412040611/ref=sr_1_1?ie=UTF8&amp;qid=1434466828&amp;sr=8-1&amp;keywords=Analysis+of+Incomplete+Multivariate+Data">Amazon</a></p>
<p>Van Buuren, S. and Groothuis-Oudshoorn, K. (2011). mice: Multivariate Imputation by Chained Equations in R. <em>Journal of Statistical Software</em>, 45(3), 1-67. <a href="http://www.jstatsoft.org/v45/i03/paper">pdf</a></p>
<hr>
<p><strong>- End of Vignette</strong></p>
<hr>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>